### ISSUE TITLE
Backspace and Delete should behave differently

### ISSUE THREAD

**Issue by thisisparker** [thisisparker/cursewords#21]
Both keys should blank out the value currently under the cursor, but backspace should `retreat` the cursor and delete should `advance` it. There's [some documented wacky behavior with these keys in `blessed`](https://blessed.readthedocs.io/en/latest/pains.html#backspace-sends-delete) but I haven't been able to get to the bottom of it.

In preliminary testing, both keys (on my box) appear to send keystrokes with the name `KEY_DELETE` and the corresponding code. However, these two keystrokes do not evaluate as equal. (Consecutive presses of backspace evaluate as equal to each other, as do consecutive presses of delete.) I haven't been able to pin down the property that differentiates the two, and it's not `name` or `code`, but that inequality leads me to believe there might be a way to distinguish.

I would welcome tips from the likes of @jquast or @thomasballinger, but also I can try to figure this out on my own!

**Comment by jquast** [comment]
It’s just your terminal emulator’s or a bash_profile-like “stty” setting, look for “backspace sends delete” etc. if you have the right keyboard and emulator then blessed detects the difference, use contrl+h to manually generate one of them, and the integer input 127 to generate the other

**Comment by jquast** [comment]
These keys may be better distinguished now, since 1.17.0, https://github.com/jquast/blessed/releases/tag/1.17.0

- bugfix: chr(127), \x7f has changed from keycode term.DELETE to the more common
match, term.BACKSPACE, #115 by @jwezel.

**Comment by thisisparker** [comment]
Oh nice! I'm planning a biggish update at some point, and I will definitely be bumping `blessed` versions. Looking forward to seeing if I can implement this with the newer version!

**Comment by jquast** [comment]
Sounds good, I’ve got a big release of wcwidth to put out the next few days but I’d really like to help with cursewords, it’s a fave of mine!

**Comment by thisisparker** [comment]
Shipped an update today and bumped `blessed` but only to 1.16.2, because it looks like 1.17 and up have some breaking changes. That's okay! I'll be figuring out what I need to change to get that and will hopefully get the better delete behavior and a whole bunch of other stuff.

**Comment by thisisparker** [comment]
I believe this is fixed with 02ac94b76d767db349571a572a1cc70959edfb4c!
