### ISSUE TITLE
Pip bundle does not package requirements.txt

### ISSUE THREAD

**Issue by rileyinman** [thisisparker/cursewords#8]
Just thought I'd let you know that this file isn't being included in the distributed tar from https://files.pythonhosted.org. I was attempting to make a PKGBUILD and it caused setup.py to fail. If that were fixed or the repo were tagged for releases, making a package would be much easier. Thanks!

**Comment by thisisparker** [comment]
oh, thank you for catching that! I'll make sure it gets fixed in the next version.

**Comment by thisisparker** [comment]
This should be fixed in the source distribution up at `1.0.3`, now live on pypi! Can you confirm you've got what you need? I'll also try to tag releases here on Github but I have to read up on that

**Comment by rileyinman** [comment]
Yes, it builds successfully now! Thanks for the speedy fixes :+1:
